version: '2.4'
services:
  luskan:
    # this is a docker-internal name, but will show up in, e.g., connections to postgres
    hostname: luskan-beta1.canfar.net
    image: bucket.canfar.net/luskan:20210408T233844
    container_name: storuv_luskan
    volumes:
      - /home/storops/uvic-site/luskan/config:/config:ro
      - asyncdata:/data:rw
      - cacerts:/config/cacerts:ro
    ports:
      - 18081:8080
    user: tomcat:tomcat
    logging:
      driver: fluentd
      options:
        fluentd-address: "tcp://prolix.canfar.net:24224"
        tag: "site.uvic.luskan"
volumes:
  asyncdata:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=100m,uid=8675309
  cacerts:
    external: true
    
    
