version: '2.4'
services:
  minoc:
    # this is a docker-internal name, but will show up in, e.g., connections to postgres
    hostname: minocnode
    image: bucket.canfar.net/minoc:0.7-20210616T225343 
    volumes:
      - ${HOME}/minoc/config:/config:ro
      - ${HOME}/cacerts:/config/cacerts:ro
    ports:
      - 18080:8080
    user: tomcat:tomcat
    
    
