#!/bin/bash

trap "echo 'ERROR running/starting haproxy'; exit -1" ERR


# log to external
#LOGDIR=/logs
#LOG=$LOGDIR/haproxy.log
CONFDIR=/usr/local/etc


echo -n "START: " 
date 

#rsyslogd


if [ -e $CONFDIR/cacerts ]; then
    echo "Configure CA bundle with extra certificates from $CONFDIR/cacerts" 
    cp $CONFDIR/cacerts/* /etc/pki/ca-trust/source/anchors/
else
    echo "No extra certificates to configure the CA bundle found" 
fi

update-ca-trust
haproxy "$@"

echo -n "init DONE: " 
date 
