version: '2.4'
services:
  baldur:
    image: bucket.canfar.net/baldur:0.2-20220526T234823
    volumes:
      - ${HOME}/baldur/config:/config:ro
      - ${HOME}/cacerts:/config/cacerts:ro
    ports:
      - 42101:8080
    user: tomcat:tomcat
    
    
